### ISSUE TITLE
Ability to specify requires packages (linux, macos)

### ISSUE THREAD

**Issue by JAicewizard** [duckdb/extension-ci-tools#49]
The FAISS extension requires both a fortran compiler and omp to build, on linux the fortran compiler is lacking and on macos its omp.

On linux the solution should be pretty easy, an extra input with `packaged (linux, amd64)`,  `packaged (linux, arm64)`, &  `packages linux, gcc4)` could be provided, to allow for installing any package that is needed for a successful build.

There is a similar situation on macos, where omp is not installed by default, and needs to be installed via brew, I would propose a similar solution of providing per-target dependencies.

I could implement this if needed, is this something that is welcome? It would be really appreciated since the I would like to get the faiss extension in the community repo.

**Comment by samansmink** [comment]
Hey @JAicewizard! Thats a good point, I've opened this PR https://github.com/duckdb/extension-ci-tools/pull/53. If that merges, I'm happy to merge a PR that adds an optional `fortran` and `omp` toolchain.

Note that I will follow up on https://github.com/duckdb/extension-ci-tools/pull/53 with a PR to the community extensions repo that allows you to specify which optional toolchains an extension requires, with that the road to adding FAISS to community should be clear

**Comment by samansmink** [comment]
Hey I'm going to close this issue because we have decided to not go down the route of passing custom packages into the reusable workflow. Your options are:

- make a PR into this repo with a clearly defined set of packages behind a flag, e.g. https://github.com/duckdb/extension-ci-tools/pull/56
- copy the reusable workflow into your extension repo and add them yourself

Note that currently the second option will not allow submitting your extension to the community repo, but we are working on a solution there, see https://github.com/duckdb/community-extensions/issues/73

**Comment by JAicewizard** [comment]
Hey thanks for the comment, I made a new PR that adds fortran and openmp as optional toolchains
